

const express = require('express');

const http = require('http');

const app = express();

const server = http.createServer(app);

const {Server} = require('socket.io');

const path = require('path');

// Used it to serve frontend 



const io = new Server(server);

app.get("/",(req,res)=>{

    res.sendFile(path.join(__dirname,'index.html'))

    // Whenever user sends '/' request we send this file (or can say display) 

})


server.listen(4000,()=>{
    console.log("Listening");
})


io.on("connection",(socket)=>{

    // socket.on("message",(data)=>{
    //     // io.emit("new-message",data);        // This also sends data to us also or the person sending the data

    //     socket.broadcast.emit('new-message',data);      // Now won't send data again to the sender 
    // })

    socket.on("message",({room,msg})=>{

        // io.to(room).emit('new-message',msg);             // Sends to all even myself who's sending the message so replaced with socket
        
        socket.to(room).emit('new-message',msg);

        // Pass socket id instead of Room number then we can use 1 to 1 chats

        // So what whatsapp does to get socketID of a person, it stores the phone number and corresponding socket id of a person

        // In an array whenever they form a WebSocket connection 

        // Then just use below line

        // socket.to(socketID).emit('new-message',msg);

        // Similarly if user opens Whatsapp in 4 tabs so we will be needed to send message in every 4 tab 
    })

    socket.on("join-room",(room)=>{
        socket.join(room);                  // Room now joined 

    })

    socket

    socket.on("disconnect",()=>{
        console.log("Disconnected from the server");
    })
})



// So whenever we open new window in browser it gives new socket id as socket = IP address + Port number

// So for now all the messages we send are being sent to all so what if we have to implement whatsapp group functionality 

// Now we need one to one messages like personal chats in whatsapp 


// Socket id generated by the server 



// Noticed a pattern whenever client emits there is emit for client and socket.on inside io.on to get that data in server

// Similarly vice versa in client we just used socket = io() so socket.on

